spring:
  datasource:
    url: Server=tcp:testdbserver1000.database.windows.net,1433;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    username: mainroot
    password: Nonecooks$19
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191
  
  
  